apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: example-app-1
  namespace: default
spec:
  image: docker.io/aimvector/example-app-1
  interval: 1m0s
  secretRef:
    name: dockerhub-credential